602/Add header back
puzzle/skills pull request #609
Opened 2024-02-20 11:49 UTC by ManuelMoeri

2024-02-21 08:20 UTC, MarcEgliP approved these changes

2024-02-23 08:20 UTC, Robin481 requested changes

2024-02-23 08:20 UTC, Robin481 commented on app/views/layouts/application.html.haml
> +              %a.align-center{:href => "https://google.com"}
Can already link to the skills github issues here.

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +}
General comment on the css:
Please do some nesting. 
`.scale-icon-08` for example doesn't need to exist in a global context. Just put it into the `navbar` class so it exists only in that context. 
Goes for the rest of the CSS classes as well. 
We probably don't want a global `nav-link` class that is not relevant in any other cases.

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +  font-size: 10px;
There exist Bootstrap classes for changing the size of text.

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +  background-color: #3b7bbe
Aren't there variables available from the puzzle shell for this?
If not define the color globally as a variable so we can use it in multiple places. Same goes for the grey below.

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +  border-left: 1px solid;
Bootstrap borders? https://getbootstrap.com/docs/4.0/utilities/borders/#border-color

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +  top: 0;
https://getbootstrap.com/docs/5.0/helpers/position/#fixed-top ?

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +.align-center {
Bootstrap class?

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +  cursor: pointer;
https://getbootstrap.com/docs/5.0/utilities/interactions/#pointer-events

2024-02-23 08:20 UTC, Robin481 commented on app/assets/stylesheets/styles.scss
> +  padding-left: 0.5rem;
Bootstrap spacing?

2024-02-23 08:20 UTC, Robin481 commented on app/views/layouts/application.html.haml
> +                  %a.nav-link.nav-pad{href: "/skills"} Skillset
Use Rails routes please

2024-02-26 08:26 UTC, Robin481 approved these changes

2024-02-26 08:26 UTC, merged