Generalize date range entities
puzzle/skills pull request #647
Opened 2024-04-05 09:34 UTC by kcinay055679

2024-04-05 22:22 UTC, kcinay055679 reviewed
Fix notes from review and make sure that the "render_new_after_save" functionallity is working. This will fix the tests

2024-04-05 22:22 UTC, kcinay055679 commented on spec/controllers/advanced_trainings_controller_spec.rb
> +      # TODO: Ask robin
Ask Robin for the best way to fix

2024-04-05 22:22 UTC, kcinay055679 commented on app/helpers/date_helper.rb
> +    entry.class.to_s.split('::').first.underscore
Extract those 2 methods to seperate helper

2024-04-05 22:24 UTC, kcinay055679 commented
Generify the files new and edit from the AdvancedTrainings so every DateRangeEntity can use them

2024-04-15 13:27 UTC, Robin481 requested changes
Next time take some time to look through your changes and figure out if you can simplify your code please :rock:

2024-04-15 13:31 UTC, kcinay055679 commented on app/controllers/advanced_trainings_controller.rb
> +  self.nesting = Person
no
https://github.com/codez/dry_crud?tab=readme-ov-file#label-Nested+Resources

2024-04-15 13:34 UTC, kcinay055679 commented on app/helpers/date_helper.rb
> +    entry.class.to_s.split('::').first.underscore
i extraced this to an other helper

2024-04-15 13:36 UTC, kcinay055679 commented on app/controllers/dry_crud/generic_model.rb
> +      :"@#{name}"
Rubocop recommended this syntax

2024-04-15 13:48 UTC, kcinay055679 commented on app/controllers/crud_controller.rb
> +  def update(**options, &block) # rubocop:disable Metrics/MethodLength
After reinsering the deleted line rubocop tells me this isn't needed and refers to the [documentation](https://docs.rubocop.org/rubocop/cops_lint.html#lintredundantcopenabledirective)

2024-04-15 13:53 UTC, kcinay055679 commented on app/helpers/generify_helper.rb
> +    entry.class.to_s.split('::').first.underscore
changed the name to obj because i use both single items and array with this funktion

2024-04-15 13:56 UTC, Robin481 approved these changes
:rock: :rocket:

2024-04-15 13:56 UTC, merged