Feature/639 create new people_skill
puzzle/skills pull request #665
Opened 2024-04-18 10:32 UTC by kcinay055679

2024-04-23 14:41 UTC, kcinay055679 commented on app/views/people/people_skills/index.html.haml
> +        = link_to "Skills ersellen", new_person_people_skill_path(@person), class: "d-flex align-items-center p-3", data: { turbo_frame: "remote_modal"}
i18n

2024-04-23 14:43 UTC, kcinay055679 commented on app/views/application/_remote_modal.html.haml
> +    %div#people-skill-wormhole
rename

2024-04-23 14:44 UTC, kcinay055679 commented on app/helpers/tab_helper.rb
> +      { title: 'CV', path: person_path(person) },
i18n

2024-04-23 14:46 UTC, kcinay055679 commented on app/javascript/controllers/people_skills_controller.js
> +        const skill_dropdown = event.target;
prob refactor

2024-05-14 07:57 UTC, Robin481 requested changes
![image](https://github.com/puzzle/skills/assets/32168247/71efcc23-2edc-4dfa-8954-539b42323026)

Two small comments, and make it look more aligned with the scroll to element pls.

2024-05-14 07:57 UTC, Robin481 commented on app/javascript/controllers/people_skills_controller.js
> +    static targets = ['switch', 'label', 'skillsDD', 'categoriesDD', 'skillTitle']
Naming... I have no Idea what `skillsDD` means

2024-05-14 07:57 UTC, Robin481 commented on app/models/people_skill.rb
> +  def skill_attributes=(attributes)
Don't put methods above all the validates, scopes etc.

2024-05-14 11:41 UTC, merged