Feature/674 limit file-size of avatar
puzzle/skills pull request #685
Opened 2024-04-30 10:48 UTC by ManuelMoeri

2024-05-03 06:29 UTC, Robin481 requested changes

2024-05-03 06:29 UTC, Robin481 commented on app/assets/images/huge_picture.jpg
No :joy: 
We can't just use any random picture, does it have some sort of Copyright on it etc. etc. etc.

Instead in the test stub the method that checks for file size and make it return `< 10mb` :smile:

2024-05-06 07:22 UTC, ManuelMoeri commented on app/assets/images/huge_picture.jpg
Thanks for this crucial input. I fixed it.

2024-05-06 07:46 UTC, Robin481 approved these changes

2024-05-06 07:46 UTC, merged