Feature/662 cleanup docker setup
puzzle/skills pull request #690
Opened 2024-05-03 12:38 UTC by kcinay055679

2024-05-14 07:58 UTC, Robin481 requested changes
I have no Idea how to test this.
And as other people might want to use this application with a dockerized setup please update the README and explain the user how to use it. Thanks!

2024-05-16 11:23 UTC, Robin481 requested changes
Update Nodesource script and fix `devise_mapping` login bug

2024-05-21 07:34 UTC, Robin481 requested changes

2024-05-21 07:34 UTC, Robin481 commented on lib/auth_config.rb
> +    def to_boolean(value)
already exists: https://github.com/puzzle/skills/blob/master/app/controllers/concerns/param_converters.rb#L7

2024-05-21 08:18 UTC, kcinay055679 commented on .github/workflows/rails.yml
> +          RAILS_DB_HOST: ${{ env.PGHOST }}
as we discussed

2024-05-21 08:18 UTC, kcinay055679 commented on config/docker/development/Rails.dockerfile
> +RUN apt-get install -y nodejs
No we still need to install nodejs via apt according to the [docs](https://github.com/nodesource/distributions?tab=readme-ov-file#using-ubuntu-2)

2024-05-21 08:41 UTC, kcinay055679 commented on app/helpers/auth_helper.rb
> +    ENV['DEVELOPMENT'] == 'true' && Rails.env.development?
we do, at least now

2024-05-21 08:57 UTC, kcinay055679 commented on docker-compose.yml
> +      sleep infinity"
no

2024-05-21 12:14 UTC, merged