Ptime mapper script
puzzle/skills pull request #737
Opened 2024-06-21 13:54 UTC by RandomTannenbaum

2024-07-12 11:15 UTC, Robin481 requested changes

2024-07-12 11:15 UTC, Robin481 commented on app/domain/ptime/assign_employee_ids.rb
> +                                      .where(email: ptime_employee_email)
add `.first` to the end of this.

2024-07-12 11:15 UTC, Robin481 commented on app/domain/ptime/assign_employee_ids.rb
> +        if matched_skills_people.empty?
after adding `.first` above you can just check for `.nil?` here
and of course rename the variable

2024-07-12 11:15 UTC, Robin481 commented on app/domain/ptime/assign_employee_ids.rb
> +        elsif matched_skills_people.one?
this is then just an `else` after adding the `.first`

2024-07-12 11:15 UTC, Robin481 commented on app/domain/ptime/assign_employee_ids.rb
> +            matched_skills_person = matched_skills_people.first
this is then not needed

2024-07-12 11:15 UTC, Robin481 commented on app/domain/ptime/assign_employee_ids.rb
> +        ptime_employee_name = "#{ptime_employee_firstname} #{ptime_employee_lastname}"
Don't assign the variables on line 28 and 29 just do the hash digging here and save those 2 lines

2024-07-12 11:15 UTC, Robin481 commented on app/domain/ptime/client.rb
> +      path = "#{path}?#{URI.encode_www_form(params)}"
don't use `path` as a variable name after passing it 
this is a URL if you ask me

2024-07-12 11:15 UTC, Robin481 commented on app/domain/ptime/client.rb
> +    rescue JSON::ParserError # rescue only JSON parsing errors
Why would that happen?

2024-07-12 11:15 UTC, Robin481 commented on config/application.rb
> +    config.active_job.queue_adapter = :delayed_job
We don't use delayed_job anymore do we? This broke it for me anways...
Remove everything related to DJ?

2025-06-27 06:02 UTC, RandomTannenbaum commented
This feature was implemented in #869

2025-06-27 06:02 UTC, closed without merging