Feature/728 language clean up
puzzle/skills pull request #743
Opened 2024-06-28 11:44 UTC by kcinay055679

2024-07-25 08:16 UTC, Robin481 requested changes
There's a lot to improve...

Furthermore 
1) the CV Search is also broken and always redirects to a Person's Skills instead of the place where the result was found... And the translation is also broken there.
2) The export Icon is not fitting
3) Interest in the skill search is not translated
4) Admin Panel is not translated
5) The CV / Skills tab don't work when opening a profile

2024-07-25 08:16 UTC, Robin481 commented on config/locales/fr.yml
> +      no_omniauth_providers: An error, no Omniauth providers are available, please contact the administrator.
French much

2024-07-25 08:16 UTC, Robin481 commented on lib/custom_translation_matchers/dry_crud_ti_scanner.rb
> +      # !send_node.loc.expression.to_json.start_with?('app/helpers')
?

2024-07-25 08:16 UTC, Robin481 commented on spec/features/cv_search_spec.rb
> +      check_search_results(Skill.model_name.human(count: 2))
again the count thing

2024-07-25 08:16 UTC, Robin481 commented on spec/features/people_skill_search_spec.rb
> -      add_and_fill_out_row("ember", 5, 4)
why remove this without seemingly any connection?

2024-07-25 08:16 UTC, Robin481 commented on spec/features/people_spec.rb
> +      expect(page).to have_current_path(person_path(bob, locale: nil))
Why do we now need this?

2024-07-25 08:16 UTC, Robin481 commented on spec/features/people_spec.rb
> +      error_msg = "Dieses Profil hat noch keine bewerteten Skills. Gehe zum Skills Tab und bewerte die für dich relevanten Skills."
Why can't we use the translation now?

2024-07-26 06:42 UTC, kcinay055679 commented on app/views/people_skills/_person_skill.html.haml
> +    %label.form-label.text-gray= PeopleSkill.human_attribute_name(:certificate)
wpu ds haut ActiveRecord isch.
ActiveRecord isch kuhl

2024-07-26 06:44 UTC, kcinay055679 commented on config/locales/crud.de.yml
> +    confirm_delete: Wollen Sie diesen Eintrag wirklich löschen?
`Ja ich will`

2024-07-26 08:02 UTC, kcinay055679 commented on Gemfile
> +gem 'deepl-rb', '~> 2.5'
No, you're right, it's not needed

2024-07-26 08:15 UTC, kcinay055679 commented on app/helpers/date_helper.rb
> +      return "- #{ti('date.today')}"
we are still using our own translation for date.today.
You can find them under gloabl.date.today in any locale file

2024-07-26 08:17 UTC, kcinay055679 commented on app/helpers/date_helper.rb
> +    (1..12).map { |m| I18n.l(DateTime.parse(Date::MONTHNAMES[m]), format: '%B') }
changed it back :)

2024-07-26 08:17 UTC, kcinay055679 commented on app/helpers/auth_helper.rb
> +  def first_path
I now use a REGEX

2024-07-26 08:31 UTC, kcinay055679 commented on config/locales/de.yml
> +        location: 'Niederlassung (für Footer):'
We do need them because of the :

2024-07-26 12:01 UTC, kcinay055679 commented
- [ ] the CV Search is also broken and always redirects to a Person's Skills instead of the place where the result was found... And the translation is also broken there.
- [ x] The export Icon is not fitting
- [ ] Interest in the skill search is not translated
- [ ] Admin Panel is not translated
- [ ] The CV / Skills tab don't work when opening a profile

2024-07-31 14:49 UTC, kcinay055679 commented on app/views/people/_search.html.haml
> +      = collection_select :person_id, :person, Person.all.sort_by {|p| p.name.downcase }, :path, :name, select_when_available(person&.path), {data:{"dropdown-target": "dropdown" , action: "change->dr
Use options_for_select

2024-08-02 07:29 UTC, kcinay055679 commented on spec/rails_helper.rb
> +    default_url_options[:locale] = I18n.default_locale
Use just I18n.locale

2024-08-05 11:55 UTC, Robin481 requested changes
Looking pretty good.

One more thing:
The languages in the dropdown should always be in their respective language. E.g. English should always be English, never Inglese, even if you are currently using Italian.

2024-08-05 11:55 UTC, Robin481 commented on app/assets/stylesheets/crud.scss
> +.icon-close { background-image: url('assets/x.svg'); }
Can we rename this file to `cancel.svg`  ? :grin: this way it atleast speaks to what it does

2024-08-05 11:55 UTC, Robin481 commented on app/controllers/people_skills/filter_params.rb
> +      skill_ids[row_id]&.to_i
Hmmm I am not sure I understand the functionality 100% but are you sure this change is fine as it changes the behaviour a bit :thinking:

2024-08-08 11:58 UTC, Robin481 approved these changes

2024-08-08 14:29 UTC, merged